### ISSUE TITLE
FileNotFoundError------- c1_wear.csv

### ISSUE THREAD

**Issue by sirisha-8** [kidozh/rnn_in_prediction_tool_wear#1]
Hi,

Main.py couldn't complete execution because of the following error.
FileNotFoundError: File b'E:\\ubuntu_file\\rnn_in_prediction_tool_wear/c1_wear.csv' does not exist

File and Line number for reference 
https://github.com/kidozh/rnn_in_forecasting_tool_wear/blob/0413aecdb6b68499d1e6b7795bf97ddce82aec75/data.py#L19

Could you please look into it and let me know the issue # @kidozh

**Comment by kidozh** [comment]
This project's tool wear data comes from PHM 2010 contest, so you can download three tool wear data,"c1.csv","c4.csv"and "c6.csv", from PHM society website(The download link seems broken) or our data download page[https://kidozh.com/projects/keras_detect_tool_wear/download_database.html](https://kidozh.com/projects/keras_detect_tool_wear/download_database.html). You should note that this data is copyrighted by PHM society.

After you obtain tool wear data, you can replace this function's return like this

```python
return 'YOUR_DOWNLOAD_DIR_PATH/c%s_wear.csv' % (self.sample_loc) 
```

That should make it.

Please feel free to contact me in this issue or open a new one if you need further help.

**Comment by sirisha-8** [comment]
Thanks for the help . problem is resolved..There is another issue which i am facing currently.

When i assigned predict to Fasle. since it didnt find any checkpoints .model is trained.In this process .when the below line is excuted 
https://github.com/kidozh/rnn_in_forecasting_tool_wear/blob/0413aecdb6b68499d1e6b7795bf97ddce82aec75/seq2seq_tool_wear/main.py#L67.

The system is throwing the following error.
![error](https://user-images.githubusercontent.com/35755214/65417187-18036300-de17-11e9-93bc-6966d5f68ad8.png)

Could you please help me in resolving this  @kidozh

**Comment by kidozh** [comment]
This is because the timestep of dataset and model don't match.

https://github.com/kidozh/rnn_in_forecasting_tool_wear/blob/0413aecdb6b68499d1e6b7795bf97ddce82aec75/seq2seq_tool_wear/main.py#L49

you can change 
```python
    model = build_simple_RNN((2,1),5,1)
```

to 

```python
    model = build_simple_RNN((10,1),20,1)
```

if you want to run a long-term RNN forecast model.

I am very sorry for this mistake and will pull a correct code to this repo. I am still busy in finding a Ph.D. admission, so it may take some days for me to correct this bug.

Thanks for asking.

Happy coding

**Comment by sirisha-8** [comment]
Thanks for the help.With the inputs provided by you.I was able to train the model. In order to test the model , link provided  by you testdata(c2,c3,c5)  seems broken.At this stage when predict is assigned to True,I am not sure of how to provide the test data  .I faced the following error during prediction.
![predict](https://user-images.githubusercontent.com/35755214/65744031-b09a2b80-e114-11e9-95fd-4db1ffa67598.png)


Could you please help me out @kidozh

**Comment by kidozh** [comment]
Firstly, we didn't provide C2, C3, C5 tool wear data because the contest didn't publish their tool wear data. So I just assume you refer to test data as we do(C1 and C4->train, C6->test). 

Secondly, because we built both short and long forecasting models by the same architecture, so in our code, we sometimes make some bugs. In this occasion,  you train the long model(receive 10, generate 20) by short model code, so it didn't work. you can reuse long term forecast evaluation part which is

https://github.com/kidozh/rnn_in_forecasting_tool_wear/blob/0413aecdb6b68499d1e6b7795bf97ddce82aec75/seq2seq_tool_wear/main_plot_paper_long.py#L73-L128

This code is originally designed for evaluation of long-term forecast model. you can just replace 

https://github.com/kidozh/rnn_in_forecasting_tool_wear/blob/0413aecdb6b68499d1e6b7795bf97ddce82aec75/seq2seq_tool_wear/main.py#L73-L123

to 

https://github.com/kidozh/rnn_in_forecasting_tool_wear/blob/0413aecdb6b68499d1e6b7795bf97ddce82aec75/seq2seq_tool_wear/main_plot_paper_long.py#L73-L128

That should work on the long term forecast model.

By the way, because main.py basically is used for short forecast model which inputs 2 time and outputs 5 time tool wear, so it may not work.  I suggest you to use `main_plot_paper_long.py` to train long-term forecast model. 

The model has few trainable parameters and is trained fast under GPU acceleration. It won't cost you a lot of time to train the RNN model over.

I may revise the repo to fix bugs in 1 or 2 week. 

Thank you for asking.

Happy Coding

**Comment by sirisha-8** [comment]
@kidozh  Thanks for the help. We were able to train and test the model.
